softeer5th/Team7-BungeoBbang

frontend/index.html, frontend/netlify.toml, frontend/src/domains/admin/App.tsx, frontend/src/domains/student/App.tsx, frontend/src/main.tsx, frontend/vite.config.ts
* test: sub domain deploy test
* test: make dummy data for test deploy
* chore: change redirects page
* fix: make connection with main
* fix: typo
* test
* test
closes #34
=> test: make ground for sub domain #34 (#1)

backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/common/exception/handler/GlobalExceptionHandler.java, backend/src/main/java/com/bungeobbang/backend/common/exception/response/ErrorResponse.java
- 전역적인 에러 처리
1. GlobalExceptionHandler 클래스에서 모든 예외를 통합적으로 처리합니다.
2. 클라이언트에 일관된 에러 응답을 반환할 수 있습니다.
- 도메인별 예외 처리
1. 도메인별로 DomainException을 상속받는 예외 클래스를 정의합니다.
- 에러 코드 관리
1. ErrorCode Enum을 통해 상태코드와 메시지를 통합 관리합니다.
아래와 같이 예외를 던져 사용합니다.
```java 
findMemberById(id)
.orElseThrow(new MemberException(INVALID_MEMBER));
INVALID_MEMBER(BAD_REQUEST,"존재하지 않는 사용자입니다.");
```
---
- ErrorCode enum, DomainException 정의
- GlobalExceptionHandler 정의, DomainException 처리
- ErrorResponse record 정의
---
-
---
- Closes #36
- 관련 링크: 
---
=> [Feat/BE/#36] global exception 설정

frontend/package-lock.json, frontend/package.json, frontend/src/domains/admin/App.tsx, frontend/src/domains/admin/pages/login/index.tsx, frontend/src/domains/student/App.tsx, frontend/src/domains/student/pages/login/index.tsx
=> chore: make routes and settings for multi domain #5

backend/src/main/java/com/bungeobbang/backend/common/infrastructure/JwtProvider.java, backend/src/test/java/com/bungeobbang/backend/member/presentation/MemberControllerTest.java
- refreshToken subject를 공백으로 수정하였습니다.
- 
---
- Refresh Token에는 사용자 정보를 포함하지 않고, 서버 측에서 만료된 Access Token을 통해 사용자를 식별한다.
- 
---
- 
- 
---
- Closes #53 
- 관련 링크: 
---
=> [Feat/Be/#53] JwtProvider 수정

backend/src/main/java/com/bungeobbang/backend/mail/service/EmailAuthService.java, backend/src/main/java/com/bungeobbang/backend/member/dto/request/MemberUniversityUpdateRequest.java, backend/src/main/java/com/bungeobbang/backend/member/dto/request/SocialLoginRequest.java, backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java
- 도커 환경에서 이메일 템플릿 읽지 못하는 오류 수정
- 
---
- [개발일지](https://www.notion.so/bside/Docker-template-0e566d7c34f84cbeb95962061fd049ec?pvs=4)에 작성해두었습니다!
- 
---
- memberController @Valid 추가
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE/#27] 도커 환경에서 이메일 템플릿 읽지 못하는 오류 수정

backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaImage.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaImageRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaCreationRequest.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaEditRequest.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaCreationResponse.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java, backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminAuth.java, backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginArgumentResolver.java, backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminLoginResolverConfig.java, backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminOnly.java, backend/src/main/java/com/bungeobbang/backend/auth/admin/AdminOnlyChecker.java, backend/src/main/java/com/bungeobbang/backend/auth/domain/Accessor.java, backend/src/main/java/com/bungeobbang/backend/common/exception/AdminException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/AgendaException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/common/exception/handler/GlobalExceptionHandler.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java, backend/src/main/resources/application-local.yml
- 🏛️ **학생회가 "답해요" 채팅방을 생성, 수정, 삭제, 종료할 수 있도록 기능 구현**  
---
- 🔒 **AOP 기반의 인가 로직 (`AdminOnlyChecker`) 구현**  
- 🧩 **학생회 ArgumentResolver 구현**  
- 💬 **"답해요" 채팅방 관련 API (생성, 수정, 삭제, 종료) 구현**  
---
- ✅ **Request DTO에 대한 validation 코드 추가**  
- ⚠️ **GlobalExceptionHandler에서 검증 오류 핸들링 메서드 추가**  
- 📝 **Javadoc 추가하여 코드 문서화 강화**  
- 📖 **Swagger 문서를 인터페이스 기반으로 분리하여 관리**  
---
- ✅ Closes #78  
- ✅ Closes #79  
- ✅ Closes #80  
- ✅ Closes #81  
- ✅ Closes #82  
---
- 📌 **API 문서 검토 요청**  
- 📜 **Swagger 및 Javadoc 중심으로 검토 부탁드립니다!**
=> [Feat/BE/#71] agenda 답해요 생성,수정,삭제,종료  API

backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaMember.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java
- 학생이 답해요 채팅방에 참가하는 API입니다.
- 
---
- AgendaController,AgendaService,AgendaMemberRepository 생성
- 
---
- 
- 
---
- Closes #87
- 관련 링크: 
---
=> [Feat/BE/#87] 학생 답하기 참가하기 API

frontend/src/components/TopAppBar.tsx, frontend/src/components/bottom-navigation/BottomNavigationItem.tsx, frontend/src/components/tab-bar/TabBar.tsx, frontend/src/domains/student/pages/agenda/chat/MoreChatButton.tsx, frontend/src/domains/student/pages/opinion/category/components/CategoryStep.tsx, frontend/src/domains/student/pages/opinion/category/components/ChatStep.tsx, frontend/src/domains/student/pages/opinion/category/index.tsx
=> [TEST/FE] 모바일뷰 테스트용 merge

backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaMember.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/LastChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/LastReadChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/MyAgendaResponse.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AgendaApi.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
- 학생이 참여한 답해요 채팅방 목록 조회 API 추가
- 참여한 채팅방의 최신 메시지와 읽지 않은 메시지 여부 조회 기능 구현
---
---
- 학생이 참여한 채팅방(`agenda_chat`)에서 `memberId` 기준으로 필터링
- `MongoTemplate`을 사용하여 최신 메시지(`lastChat`) 조회
- 읽지 않은 메시지(`hasNew`) 여부 계산 로직 추가
- swagger 명세
- fetct join을 이용하여 n+1 문제 해결
- 마지막 채팅이 없을 경우 조회 안되는 문제 해결
---
- Closes #99
- 관련 링크: [JIRA/Trello Issue URL]
---
=> [Feat/BE/#99] 학생이 참여한 답해요 채팅방 목록 조회 API

backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaChatRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaChatResponse.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/response/AgendaDetailResponse.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AgendaApi.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/common/util/ObjectIdSerializer.java, backend/src/main/java/com/bungeobbang/backend/common/util/ObjectIdTimestampConverter.java
- 학생회/학생가 특정 답해요 채팅방의 채팅을 조회
- 학생회/학생이 특정 답해요 상세조회
---
- MongoRepository를 이용하여 채팅 무한스크롤 기능 구현
- 
---
- `AgendaChat` MongoDB Entity로 변경
- 
---
- Closes #110 
- 관련 링크: 
---
=> [Feat/BE/#110] 답해요 채팅 조회 API

backend/src/main/java/com/bungeobbang/backend/common/config/RedisConfig.java, backend/src/main/java/com/bungeobbang/backend/common/infrastructure/RedisClient.java
- jedis -> lettuce로 redisCLient 변경했습니다.
- 
---
- jedis -> lettuce
- username, password 환경변수 추가
---
- Closes #55 
- 관련 링크: 
[Jedis vs Lettuce](https://www.notion.so/bside/Redis-sync-vs-Async-31f4a8d2750743ad91c1dcd2debfaa07?pvs=4)
---
=> [Refactor/BE#55] RedisClient 변경

backend/build.gradle, backend/src/main/java/com/bungeobbang/backend/badword/domain/BadWord.java, backend/src/main/java/com/bungeobbang/backend/badword/domain/repository/BadWordRepository.java, backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java, backend/src/main/java/com/bungeobbang/backend/chat/interceptor/WebSocketAuthInterceptor.java, backend/src/main/java/com/bungeobbang/backend/common/config/WebSocketConfig.java, backend/src/main/java/com/bungeobbang/backend/common/exception/BadWordException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
- 웹소켓 설졍
- 금칙어 시스템
---
- 
- 
---
- 
- 
---
- Closes #128 
- closes #129 
- closes #130 
- 관련 링크: 
---
=> [Feat/BE/#130] 금칙어 시스템

backend/build.gradle, backend/src/main/java/com/bungeobbang/backend/badword/domain/BadWord.java, backend/src/main/java/com/bungeobbang/backend/badword/domain/repository/BadWordRepository.java, backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java, backend/src/main/java/com/bungeobbang/backend/chat/interceptor/WebSocketAuthInterceptor.java, backend/src/main/java/com/bungeobbang/backend/common/config/WebSocketConfig.java, backend/src/main/java/com/bungeobbang/backend/common/exception/BadWordException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/test/java/com/bungeobbang/backend/BackendApplicationTests.java, backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImplTest.java, backend/src/test/java/com/bungeobbang/backend/member/presentation/MemberControllerTest.java, backend/src/test/resources/application-test.yml
- 테스트 안 돌아가는 에러 수정했습니다ㅏㅏ
- 
---
=> [Hotfix/BE] 테스트 실패 수정

backend/src/main/java/com/bungeobbang/backend/member/dto/response/AccessTokenResponse.java, backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java, backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
- 어세스토큰, 리프레시 토큰을 요청받아 어세스토큰을 재발급한다.
- 
---
- memberService extend 메서드 추가
- 
---
- 
- 
---
- Closes #140 
- 관련 링크: 
---
=> [Feat/BE/#140] 로그인 연장 API

backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaMemberRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/CustomAgendaChatRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/dto/request/AgendaChatRequest.java, backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/chat/config/WebSocketConfig.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AdminConnectEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AdminWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaAdminEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaMemberEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/MemberConnectEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/MemberWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/service/AgendaRealTimeChatService.java, backend/src/main/java/com/bungeobbang/backend/chat/service/MessageQueueService.java, backend/src/main/java/com/bungeobbang/backend/chat/service/RedisMessageQueue.java, backend/src/main/java/com/bungeobbang/backend/chat/type/RoomType.java, backend/src/main/java/com/bungeobbang/backend/chat/type/SocketEventType.java, backend/src/main/java/com/bungeobbang/backend/common/config/ObjectMapperConfig.java, backend/src/main/resources/application-local.yml
- 웹소켓 설정
- redis pub/sub
---
- eventPublisher를 이용하여 채팅과 관련된 이벤트를 생성하고 `AgendaEventListener`,`AgendaRealTimeChatService`에서 각 이밴트를 처리하도록 구현했습니다
`AdminConnectEvent` 학생회 웹소켓 연결 이벤트
`AdminWebsocketMessage` 학생회 웹소켓 메세지
`AgendaAdminEvent` 학생회 답해요 이벤트
`AgendaMemberEvent` 학생 답해요 이벤트
`MemberConnectEvent` 학생 웹소켓 연결 이벤트
`MemberWebsocketMessage` 학생 웹소켓 메세지
---
- 채팅방 이벤트 정의
- websocket handler 구현
- 답해요 실시간 채팅 기능
---
- Closes #122 
- Closes #128 
- Closes #129 
- Closes #142 
- Closes #143 
- Closes #144
- Closes #145 
- Closes #146
- 관련 링크: 
---
=> [Feat/BE/#121] websocket

backend/build.gradle, backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaAdminLastReadChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AdminLastReadChatRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaChatRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaLastReadChatRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java, backend/src/main/java/com/bungeobbang/backend/common/config/S3Config.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ImageException.java, backend/src/main/java/com/bungeobbang/backend/image/domain/ImageFile.java, backend/src/main/java/com/bungeobbang/backend/image/dto/request/ImageDeleteRequest.java, backend/src/main/java/com/bungeobbang/backend/image/dto/response/ImageResponse.java, backend/src/main/java/com/bungeobbang/backend/image/infrastrcture/S3ImageService.java, backend/src/main/java/com/bungeobbang/backend/image/presentation/ImageController.java, backend/src/main/java/com/bungeobbang/backend/image/service/ImageService.java, backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceTest.java
- image 업로드,삭제 API 구현
- 
---
- 이미지 업로드 기능 추가
- 이미지 삭제 기능 추가
---
- `CompletableFuture`를 사용하여 비동기 이미지 업로드/삭제 구현
- `Javadoc` 추가
---
- Closes #155
- 관련 링크: 
---이미지 업로드
---이미지 삭제
---
=> [Feat/BE/#155] image 업로드,삭제 API

.github/workflows/gradle.yml, backend/Dockerfile, backend/build.gradle, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionLastReadRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/AdminOpinionController.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java
- 말해요 채팅방 리스트 조회 API 성능 개선
- workflow/gradle.yml 추가
---
---
- 
- 
---
- Closes #149 
- Closes #152 
---
=> [Feat/BE/#149] 말해요 채팅방 리스트 성능개선, workflow 추가

.github/workflows/gradle.yml
workflow 수정
---
도커 이미지 삭제
scc9811/onu -> scc9811/onu:none
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] workflow 수정

backend/src/main/java/com/bungeobbang/backend/aop/HttpRequestLoggingAspect.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/MemberWebsocketMessage.java
- 오류 해결
- 
---
- MemberWebsocketMessage json format 설정
- 로깅을 위해 aop 클래스 추기!!!
---
- Closes #
- 관련 링크: 
---
=> [Hotfix/BE/#121] websocket localDateTime 파싱 오류 해결

.github/workflows/gradle.yml, backend/src/main/java/com/bungeobbang/backend/opinion/domain/OpinionChat.java, backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/OpinionDetailResponse.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/OpinionChatApi.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
- 말해요 api 수정
- workflow에 사용하지 않는 도커 이미지 삭제 명령어 수정
---
---
- Closes #161 
- 관련 링크: 
---
=> [Feat/BE/#161] 말해요 api 수정

frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/domains/student/App.tsx, frontend/src/domains/student/pages/chat-page/styles.ts, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useImageUpload.ts, frontend/src/utils/chat/formatChatData.ts
- student/opinion/chat 구현
- useEmageUpload 커스텀훅 구현
- 채팅 포매팅 util 구현
---
=> [REFACTOR/FE] 공통작업을 위한 중간 PR

backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java, backend/src/main/java/com/bungeobbang/backend/chat/config/WebSocketConfig.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java
- sockJs 추가
- 답해요 수정 오류 해결
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Feat/BE]  sockJS 추가

backend/src/main/java/com/bungeobbang/backend/chat/config/WebSocketConfig.java, backend/src/main/java/com/bungeobbang/backend/chat/interceptor/WebSocketAuthInterceptor.java
- sockjs 없이 그냥 웹소켓 연결으로 변경
- 다시 헤더에 토큰 포함하도록 변경
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/BE] : sockjs 삭제

backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/event/opinion/OpinionEventListener.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/interceptor/WebSocketAuthInterceptor.java
- 웹소켓 연결 시 sec-websocket-protocol 사용하도록 변경
- createdAt 시점 변경 ( 서버에서 메시지 받은 시점 )
---
- 
-
=> [Fix/BE] 소켓 초기화 변경

backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
- objectMapper로 맵핑된 request로 requestContainsCreatedAt 새로운 dto 생성하도록 변경
---
- 
- 
---
- Opinion Prefix 변경
- O -> O_
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] createdAt 수정

backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java, backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminDisconnectEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberDisconnectEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/service/RedisMessageQueue.java
- 웹소켓 연결 해제 시 레디스 구독도 해제하여 리소스 낭비를 방지한다.
- 
---
- 학생,학생회 웹소켓 연결 해제 시 참여하고 있는 답해요 채팅방에 대한 구독을 모두 해지한다. 
- 
---
---
- Closes #189 
- 관련 링크: 
---
=> [Feat/BE/#189] 답해요 레디스 구독 관리

backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaAdminEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/event/agenda/AgendaMemberEvent.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
- 실시간 채팅 도중 채팅방 종료/삭제 상황을 반영하였습니다.
- 
---
- 답해요 메아리 전송을 서비스 로직으로 이동하였습니다.
- 채팅 전송 전 채팅방 존재 여부/종료여부를 확인합니다.
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Feat/BE/#193] 채팅 전송 시 종료/삭제 여부 검증

backend/src/main/java/com/bungeobbang/backend/common/config/CorsConfig.java
- 배포 도메인 cors 추가하였습니다!!!1
- 
---
- 
- 
---
- Closes #203
- 관련 링크: 
---
=> [Feat/BE/#203] 배포 cors 추가

backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
- 학생은 햇는데 학생회는 안돼잇던 채널 구독 최적화 했습니다
- 
---
- active한 채팅방만 구독하도록 수정하였습니다.
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] 학생회 채널 구독 최적화

backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java, backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java, backend/src/main/java/com/bungeobbang/backend/member/dto/request/MemberUniversityUpdateRequest.java, backend/src/test/java/com/bungeobbang/backend/agenda/service/AgendaServiceConcurrencyTest.java, backend/src/test/resources/data/agenda_participate_test.sql
- 답해요 생성,수정 시 제목이나 내용에 금칙어가 있을 경우 에러를 던진다.
- 답해요 참가하기 동시성 제어
---
- 금칙어 필터링
- 동시성 제어
---
- badwordService 메서드 추가
- 
---
- Closes #218 
- closes #219 
- 관련 링크: 
---
=> [Feat/BE/#218] 답해요 생성/수정 시 금칙어 필터링, 참가하기 동시성 제어

frontend/src/components/Chat/ChatSendField.tsx, frontend/src/components/bottom-navigation/BottomNavigation.tsx, frontend/src/config/auth.ts, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx, frontend/src/domains/student/pages/opinion/category/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useImageUpload.ts, frontend/src/hooks/useSocketManager.ts, frontend/src/main.tsx, frontend/src/store/socketStore.ts, frontend/src/utils/chat/formatChatData.ts
- 이미지 업로드 로직 수정 ( s3 url .env 에 저장 )
- 학생회 채팅시 enter, leave 등 소켓 이벤트 전달 
---
=> [FE/FIX] 말해요 채팅관련 버그 fix 

frontend/src/components/BottomSheet.tsx, frontend/src/components/Chat/ChatSendField.tsx, frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/components/Chat/TextBadge.tsx, frontend/src/domains/admin/App.tsx, frontend/src/domains/admin/pages/agenda/chat/index.tsx, frontend/src/domains/admin/pages/agenda/components/CategoryContent.tsx, frontend/src/domains/admin/pages/agenda/components/ChatRoomCardData.tsx, frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx, frontend/src/domains/admin/pages/agenda/components/MoreContent.tsx, frontend/src/domains/admin/pages/agenda/components/SubTitleText.tsx, frontend/src/domains/admin/pages/agenda/create/index.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/agenda/util/ChatRoomMapper.tsx, frontend/src/domains/admin/pages/chat-page/ChatData.tsx, frontend/src/domains/admin/pages/chat-page/index.tsx, frontend/src/domains/admin/pages/login/index.tsx, frontend/src/domains/admin/pages/login/styles.ts, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/chat/index.tsx, frontend/src/domains/student/pages/agenda/index.tsx, frontend/src/domains/student/pages/my/index.tsx, frontend/src/hooks/useInfiniteScroll.tsx, frontend/src/utils/chat/formatChatData.ts
- 학생회 답해요 채팅방 위아래로 무한 스크롤
- 바텀시트 배경 안 보이는 문제 해결 & 애니메이션 추가
---
- 
- 
---
- 
- 
---
- Closes #214 
- 관련 링크: 
---
=> [FEAT/FE/214] 학생회 답해요 채팅방 위아래로 무한 스크롤

frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/admin/pages/opinion/entry/types.ts, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/main.tsx
- 말해요 리마인드 기능 추가
- 이미지 프리뷰 추가
- 각종 버그 수정
---
- 리마인드 기능 추가 및 테스트 완료 
- 채팅방 내부에 존재하는 이미지 클릭시 프리뷰 화면 등장
---
- 
- 
---
- Closes #223
- 관련 링크: 
---
=> [FEAT/FE/#223] 말해요 리마인드 및 이미지 프리뷰

backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java, backend/src/main/java/com/bungeobbang/backend/common/config/S3Config.java
- ec2에 부여된 role을 사용하도록 변경
- 
---
- ec2에 부여된 role을 사용하도록 변경
- 
---
- 중복 코드 제거
---
- Closes #
- 관련 링크: 
---
=> [FixBE] s3 role 강제 사용

backend/src/main/java/com/bungeobbang/backend/opinion/domain/AnsweredOpinion.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/AnsweredOpinionRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomAnsweredOpinionRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionStatisticsResponse.java, backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/AdminOpinionController.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/api/AdminOpinionApi.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
- 말해요 월간/연간 통계 기능 추가
---
- answered_opinion 컬렉션 추가
- 학생회 답변 시 해당 컬렉션에 upsert
- 통계 조회 시 university와 objectId기반 기간(1달/1년) 필터링
---
- swagger 추가
- 마지막 읽은 채팅 id 업데이트 테스트코드 수정
---
- Closes #233 
---
=> [Feat/BE/#233] 말해요 통계 기능 추가

frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/domains/admin/pages/agenda/chat/index.tsx, frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/index.tsx, frontend/src/domains/student/pages/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/main.tsx, frontend/src/store/socketStore.ts
- 학생회, 학생 답해요 소켓 연결
---
- 입장시 entry, 나갈시 leave 적용/..,,
- 채팅 보낼시 chat 적용
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FEAT/FE/#222] 답해요 소켓 연결  

frontend/src/domains/admin/pages/chat-page/index.tsx, frontend/src/domains/student/pages/agenda/chat/index.tsx, frontend/src/domains/student/pages/agenda/index.tsx, frontend/src/domains/student/pages/agenda/util/ChatRoomCardMapper.tsx, frontend/src/domains/student/pages/chat-page/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FE/TEST] 웹소켓 연결

frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/hooks/useScrollBottom.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [TEST/FE] 배포 테스트용 PR

frontend/src/domains/admin/pages/agenda/chat/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 채팅방 초기 조회시 initial 옵션 추가

frontend/src/domains/admin/pages/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 모바일 뒤로가기 스와이프시 leave 소켓 메시지 전송.
- 
---
- handle leave 함수로 leave 메시지 전송을 관리 
`  const hasLeft = useRef(false);
const handleLeave = useCallback(() => {
if (!hasLeft.current) {
socketManager('AGENDA', 'LEAVE', Number(localStorage.getItem('member_id')), 'ADMIN');
hasLeft.current = true;
}
}, [socketManager]);
useEffect(() => {
return () => {
handleLeave();
};
}, [handleLeave])`
---
- 
- 
---
- Closes #245
- 관련 링크: 
---
=> [FEAT/FE/#245] 모바일 뒤로가기 스와이프시 leave 소켓 메시지 전송.

frontend/src/domains/student/pages/chat-page/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: build error

backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaService.java
- 사용자가 현재 채팅방을 읽고 있을때에는 최신 데이터를 반환한다.
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE/#239] 실시간으로 읽고 있을 때 최신데이터 반환

frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: send chat load api with scroll param

frontend/src/domains/admin/pages/agenda/chat/index.tsx, frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx, frontend/src/domains/admin/pages/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/chat-page/index.tsx, frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useEnterLeaveHandler.ts, frontend/src/store/socketStore.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> 웹소켓 연결 끊김 이슈, enter, leave dependency 제거 

frontend/src/hooks/useEnterLeaveHandler.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: enter leave handler room id

frontend/src/store/socketStore.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: make member id string to number

backend/src/main/java/com/bungeobbang/backend/auth/JwtProvider.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/MemberOpinionController.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java, backend/src/test/java/com/bungeobbang/backend/opinion/fixture/OpinionFixture.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
- 말해요 api 수정
- 
---
- 첫 채팅 등록(== 채팅방 생성) 요청 시 금칙어 필터링 추가
- 채팅내역 조회 변경
- 리마인드 중복 요청 시 예외 처리
---
- 어세스/리프레시 토큰 만료시간 서로 바뀌어있던 부분 수정
---
- Closes #250 
---
=> [Feat/BE/#250] 말해요 api 수정

backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java
- 위로 스크롤 할 경우 내림차순 정렬 후 reverse로 수정합니다.
- 
---
- maxObjectId일때도 최신 10개를 조회하기 위해 내림차순으로 정렬합니다.
- 
---
- 제가 오해했네요 죄송합니다......,,
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] up scroll 수정

backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java
- 채팅 내역 조회 스크롤 수정
---
- scroll == UP || (INITIAL && chatId==MAX_OBJECT_ID) 인 경우 조회 로직 수정
- 기존 : 오름차순 정렬 후 limit -> 반환
- 변경 : 내림차순 정렬 후 limit -> reverse -> 반환
=> [Fix/BE] : 채팅 내역 조회 스크롤 수정

backend/src/main/java/com/bungeobbang/backend/agenda/domain/Agenda.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/AgendaChat.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/listener/AgendaEventListener.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaChatService.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java, backend/src/test/java/com/bungeobbang/backend/agenda/service/AdminAgendaServiceTest.java
- 답해요 수정 시 첫번째 채팅도 수정한다
- 
---
- agenda 테이블에 첫번째 채팅 추가 저장
- 학생회가 답해요 생성 시 시작날짜가 오늘인 답해요만 레디스 구독 시작
- 
---
- 진행중인 답해요 find 쿼리 오류 수정
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] agenda update 채팅 수정

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/chat/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/opinion/category/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: build 에러 해결

frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> 말해요 무한 스크롤 옵션 빠져있는 거 수정

backend/src/main/java/com/bungeobbang/backend/chat/event/common/AdminWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/event/common/MemberWebsocketMessage.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/AdminWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/handler/MemberWebSocketChatHandler.java, backend/src/main/java/com/bungeobbang/backend/chat/type/SocketEventType.java, backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
- 웹소켓 에러 응답에 에러코드 추가
- 
---
- websocketMessage에 에러코드 추가
- ping 요청 시 pong 응답
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Feat/BE] pong 응답, 에러코드 추가

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/create/index.tsx, frontend/src/domains/admin/pages/agenda/util/ChatRoomMapper.tsx
- 채팅방 추가할 때 선택한 날짜보다 하루 전으로 저장이 되는 문제 해결
- 로컬 시간대가 아니라 ISO 시간대로 설정되어서 다르게 저장되고 있었음
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 채팅방 추가할 때 날짜 문제

frontend/src/components/Chat/ChatSendField.tsx, frontend/src/main.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> feat: send message when enter key down

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: 안 쓰는 코드 주석

backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/Opinion.java, backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
- 채팅 개수 검증 로직 추가
---
- 학생이 채팅 시 chatCount++
- 학생회가 채팅 시 chatCount = 0
- 3회 초과해서 채팅 전송 시 에러 반환
---
- Closes #286 
- 관련 링크: 
---
=> [Feat/BE/#286] : 채팅 개수 검증 로직 추가

frontend/src/components/Chat/ChatSendField.tsx
- onkeydown double sending issue for korean
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] onkeydown double sending issue for korean

frontend/index.html, frontend/src/components/CategoryIcon.tsx, frontend/src/components/Chat/ChatSendField.tsx, frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/EmptyContent.tsx, frontend/src/components/TopAppBar.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/styles.ts, frontend/src/domains/admin/pages/agenda/chat/index.tsx, frontend/src/domains/admin/pages/agenda/components/ChatRoomListItem.tsx, frontend/src/domains/admin/pages/agenda/components/MoreContent.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/login/index.tsx, frontend/src/domains/admin/pages/login/styles.ts, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/student/pages/agenda/chat/index.tsx, frontend/src/domains/student/pages/agenda/components/Banner.tsx, frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useInfiniteScroll.tsx, frontend/src/hooks/useScrollBottom.tsx, frontend/src/main.tsx, frontend/src/types/ChatCategoryType.tsx
- 이미지 깨짐 현상 해결 
- 엔터로 send 시 한글 두번 보내지는 버그 해결
- 모바일 뷰에서 채팅시 확대되는 기능 삭제 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 이미지 깨짐 현상, 엔터 버그 등 버그 해결

frontend/dev-dist/sw.js, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/store/socketStore.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] opinion chat lender when student start chatting

frontend/src/components/Chat/ChatSendField.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx, frontend/src/domains/student/pages/my/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/store/socketStore.ts, frontend/vite.config.ts
✅ | 소켓 구독 풀림 문제
✅ | 로그아웃 버튼 연결
✅ | 학생 말해요 상단바에 이름적기
✅ | my 에서 학생 답해요 들어가면 나가기 버튼 안뜸
✅ | 리마인드 아이콘 처리
✅ | 자동 회전 막기
✅ | 핸드폰 엔터 -> 줄바꿈
✅ | 핑퐁 리시버
---
- 
- 
---
- 
- 
---
- Closes #303
- 관련 링크: 
---
=> [FIX/FE/#303] 소켓 연결 문제 및 각종 버그 해결

frontend/package-lock.json, frontend/package.json, frontend/src/components/Chat/ChatSendField.tsx, frontend/src/domains/student/pages/opinion/category/index.tsx, frontend/src/domains/student/pages/opinion/entry/styles.ts, frontend/src/hooks/useImageUpload.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 모바일 이미지 기능 테스트 

frontend/index.html, frontend/package-lock.json, frontend/package.json, frontend/src/components/Chat/ChatSendField.tsx, frontend/src/hooks/useImageUpload.ts
- heic 파일 및 heif  호환성 문제 해결
- 
---
- heic2any 라이브러리 통해서 호환성 문제 해결
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE/#317] convert heic heif image to jpeg

backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/common/exception/handler/GlobalExceptionHandler.java, backend/src/main/java/com/bungeobbang/backend/common/exception/response/ErrorResponse.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java
- 말해요 통계 테스트코드 작성
- 에러코드 반환 추가
---
- 말해요 통계 api 테스트코드 작성
---
- 
- 
---
- Closes #320 
---
=> [Test/BE/#320] 말해요 통계 테스트코드 작성 & 에러코드 반환 추가

frontend/package-lock.json, frontend/package.json, frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/components/ChatToast.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/ChatData.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useScrollBottom.tsx, frontend/src/main.tsx, frontend/src/utils/chat/chat_const.ts, frontend/src/utils/chat/formatChatData.ts
- 무한 스크롤 최신일 때 스크롤 마지막이 아니라 첫번째 채팅으로 포커싱 되는 문제 
- 새로운 채팅이 왔다는 알림 누르면 맨 밑으로 이동
- 날짜 구분선 추가요청 받을 때 중복이면 사라지도록
---
- 내가 보낼 때는 무조건 맨 밑으로 이동
- 렌더링 하기 전에 이전 채팅 데이터랑 비교했을 때 날짜가 다르면 날짜 구분선을 추가하도록 수정
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FEAT/FE/316] 무한스크롤 버그

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/main.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE/316] 빌드 에러 수정

frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/utils/chat/formatChatData.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 학생 학생회 반대로 되는 거 & invalid data log 찍기

frontend/src/components/Chat/SenderChat.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/admin/pages/opinion/entry/OpinionItem.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/agenda/index.tsx, frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx, frontend/src/domains/student/pages/my/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/utils/chat/formatChatData.ts, frontend/src/utils/chat/lastChatTime.ts
- 날짜 구분선 소켓 메시지가 오면 invalid date 뜨는 오류 해결
- 마지막 채팅 시간 오늘이면 시간, 다른 날이면 날짜가 드도록 변경
- 탭 바 위치 유지
- 
---
- 
- 
---
- 이미 입장한 채팅방 입장할 때 잠깐 채팅방 입장 모달 뜨는 거 없앰
- 내가 보낸 메시지의 사진 렌더링 순서 반대되는 거 뒤집음
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 날짜 구분선 오류 

frontend/src/domains/admin/pages/opinion/entry/OpinionItem.tsx, frontend/src/domains/student/pages/my/components/ChatPreviewItem.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 
- 안 쓰는 코드 삭제
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 빌드 오류 해결

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 학생 말해요 최신부터 조회할 때 학생,학생회 바뀌어서 렌더링되는 문제 해결
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 학생,학생회 바꿔서 랜더링하는 거 수정

frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 리마인드 버그 해결
- 
---
- chatData 를 의존성으로 가지는 useEffect 를 통해 chatData 변경시 마다 리마인드 enable 여부 판단
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 리마인드 버그 해결

frontend/package-lock.json, frontend/src/components/Chat/ChatSendField.tsx, frontend/src/components/Chat/ImagePreview.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/components/ErrorBoundary.tsx, frontend/src/components/Toast/index.tsx, frontend/src/contexts/ErrorContext.tsx, frontend/src/domains/admin/App.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/components/SendDialog.tsx, frontend/src/domains/admin/pages/agenda/styles.ts, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/App.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/agenda/components/styles.ts, frontend/src/domains/student/pages/agenda/styles.ts, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useError.ts, frontend/src/main.tsx, frontend/src/types/error.ts, frontend/src/utils/api.ts, frontend/src/utils/errorHandler.ts
- 에러 바운더리 전역적으로 구현
- 이미지 프리뷰 화면에서 스와이프 작동
- 아젠다 채팅방 아이템 비율깨짐 및 화면 넘어감 해결
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FEAT/FE] 에러 핸들링 및 이미지 프리뷰 스와이프 구현 및 아젠다 버그 픽스 

backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/CustomOpinionChatRepository.java
- 채팅내역 응답 개수 10개 -> 15개로 수정
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] 말해요&답해요 채팅내역 응답 개수 변경

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/agenda/util/ChatRoomMapper.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useInfiniteScroll.tsx, frontend/src/hooks/useScrollBottom.tsx, frontend/src/utils/chat/chat_const.ts
- 무한스크롤 중복 채팅, 스크롤 튀어오름, up/down 요청 안 됨 등등 버그 해결
- 
---
- 
- 
---
- 학생회 답해요 진행 중인데 종료되었다고 뜨는 문제 해결
- 종료 날짜로 관리했는데 요청 status로 관리하도록 변경
- 
---
- Closes #258 
- 관련 링크: 
---
=> [FIX/FE/258] 무한스크롤 버그 오류 해결

frontend/src/domains/student/pages/my/util/AgendaChatRoomMapper.tsx
- my에서 isEnd를 isInProgress로 저장할 때 반대로 저장하고 있던 거 변경
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE/258]: isEnd 반대로 저장

backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
- 진행 중 안건 조회 쿼리 수정했어용
- 
---
- agendaRepository 수정
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [HotFix/BE] 학생회 진행중 안건 구독 수정

backend/src/main/java/com/bungeobbang/backend/agenda/service/MemberAgendaService.java
- isEnd 버그 수정해ㅑㅅ습니다...
- 
---
- isEnd 조건문
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] 학생 내 답해요 조회 진행안건 버그 수정

backend/src/main/java/com/bungeobbang/backend/badword/AhoCorasick.java, backend/src/main/java/com/bungeobbang/backend/badword/domain/AllowedWord.java, backend/src/main/java/com/bungeobbang/backend/badword/domain/repository/AllowedWordRepository.java, backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java, backend/src/main/java/com/bungeobbang/backend/common/exception/BadWordException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/DomainException.java, backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java
- 금칙어 유무만 판단했던 기존 방식에서, 금칙어 키워드 추출 기능 추가
---
- 영어 금칙어의 경우 case insensitive 하도록 변경
< 실행 순서 >
1. 입력 텍스트를 소문자로 변환하여 일관된 비교를 수행.
2. `badWordsTrie`를 통해 텍스트에서 금칙어 목록을 찾고, 해당 단어들의 등장 횟수를 저장.
3. `allowedWordsTrie`를 통해 허용된 단어 목록을 찾고, 해당 단어들의 등장 횟수를 저장.
4. 금칙어 목록을 순회하면서 아래 조건을 만족하는 경우 예외 발생:
- 해당 금칙어가 `allowedWords`(허용된 단어 목록) 중 하나에 포함되지 않거나,
- 포함된 경우라도 `badWord`의 개수가 `allowedWord`의 개수보다 많을 때.
---
- Closes #352 
- closes #339 
- 관련 링크: 
---
=> [Feat/BE/#352] 금칙어 키워드 추출

backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/AdminAgendaChatRepositoryImplTest.java, backend/src/test/java/com/bungeobbang/backend/agenda/domain/infrastructure/MemberAgendaChatRepositoryImplTest.java, backend/src/test/resources/data/member_agenda_chat_scroll.json
- 스크롤 개수 변경에 따라 테스트 코드 수정했습니다.
- 
---
- 테스트 코드 수정
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/BE] 테스트코드 수정

backend/src/main/java/com/bungeobbang/backend/badword/service/BadWordService.java
- 메시지에서 추출한 '허용 단어'들 중 금칙어가 포함된 허용 단어가 존재하지 않는 경우 또한 예외 발생하도록 수정
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] 매칭되는 allowedWord가 없는 badWord 또한 예외 발생하도록 수정

frontend/src/components/tab-bar/TabBar.tsx, frontend/src/components/tab-bar/TabBarCotainer.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/agenda/styles.ts, frontend/src/domains/admin/pages/statistics/index.tsx, frontend/src/domains/student/pages/my/index.tsx, frontend/src/domains/student/pages/my/styles.ts, frontend/src/stories/TabBar.stories.tsx, frontend/src/stories/TabBarContainer.stories.tsx
- 탭바를 통해 컨텐츠 이동할 때 슬라이딩으로 이동 가능하도록 함
- 원래는 화면은 움직이지 않고 사용자가 일정 범위 이상 스와이프를 하면 그 때 탭이 넘어감
- 지금은 사용자가 스와이프하면 화면이 따라감
- 탭바와 콘텐츠를 TabBarContainer Component로 분리함
---
- 
---
- 화면의 절반 이상을 스와이프해야지 다음 화면으로 넘어갑니다.
- TabBarContainer story도 만듦
---
- Closes #361 
- 관련 링크: 
---
=> [FEAT/FE/361] 탭바 슬라이딩

frontend/src/domains/admin/pages/statistics/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE/361] 안 쓰는 코드 삭제

backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
- 말해요 채팅 개수 제한 로직 변경
- 
---
기존 : 채팅마다 chatCount update, 검증
변경 : 채팅마다 mongodb에서 최신 채팅 3개 검증
---
- 
- 
---
- Closes #368 
- 관련 링크: 
---
=> [Fix/BE/#368] 말해요 채팅 개수 제한 로직 변경

backend/src/main/java/com/bungeobbang/backend/common/config/S3Config.java, backend/src/main/java/com/bungeobbang/backend/image/dto/request/PresignedUrlRequest.java, backend/src/main/java/com/bungeobbang/backend/image/dto/response/PresignedUrlResponse.java, backend/src/main/java/com/bungeobbang/backend/image/infrastrcture/S3ImageService.java, backend/src/main/java/com/bungeobbang/backend/image/presentation/ImageController.java, backend/src/main/java/com/bungeobbang/backend/image/service/ImageService.java
- 이미지 업로드 front에서 하기 위해 presigned url을 생성한다.
- 
---
- 
- 
---
- 
- 
---
- Closes #374 
- 관련 링크: 
---
=> [Feat/BE/#374] s3 presigned url 발급

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx
- 이전에는 소켓 데이터가 오면 무조건 최신 데이터 15개를 가져오도록 함
- 상대방이 최신 데이터를 다 받아온 상태에서 소켓 메시지가 오는 경우에는 직접 추가하여 API요청을 줄임
---
- 
- 
---
- '새로운 채팅이 도착했습니다' 알림 누르면 호출되는 함수 변경 (이전 함수는 hasUpMore를 true로 풀어주지 않아서 위로 스크롤이 막힘)
- 
---
- Closes #376 
- 관련 링크: 
---
=> [FEAT/FE/376] 소켓 데이터 추가 최적화

frontend/src/hooks/useImageUpload.ts
- 이미지 업로드 방식을 presigned url 으로 변경
---
- 클라 -> 서버 -> S3 -> 서버 -> 클라
- 클라 -> S3 -> 클라 
- 위와 같이 서버를 거치지 않고 성능 향상을 이루어냄
---
- 
- 
---
- Closes #377 
- 관련 링크: 
---
=> [FEAT/FE/#377] presigned url S3 image upload

frontend/src/components/Chat/ChatSendField.tsx, frontend/src/components/text-field/TextField.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/main.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] agenda 진행전 안건 lender error

backend/src/main/java/com/bungeobbang/backend/opinion/listener/OpinionEventListener.java
- 학생회가 실시간으로 말해요를 듣고잇기때문에 입장 시 구독하는 메서드는 삭제했습니다.
- 
---
- 입장 시 구독 없앰
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE/#393] opinion enter 구독 삭제

frontend/src/components/TopAppBar.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/student/pages/agenda/index.tsx, frontend/src/domains/student/pages/opinion/entry/index.tsx, frontend/src/domains/student/pages/opinion/entry/styles.ts, frontend/src/index.css
- 캐싱, 소켓 간 데이터 동기화 문제 해결
- 
---
- 소켓에서 데이터를 받는 경우 inval query  통해서 cache 초기화 진행
- 
---
- UI 버그 수정
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] query cache 관련 버그 해결

backend/src/main/java/com/bungeobbang/backend/common/exception/ErrorCode.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionChatRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/AdminOpinionsInfoResponse.java, backend/src/main/java/com/bungeobbang/backend/opinion/dto/response/MemberOpinionsInfoResponse.java, backend/src/main/java/com/bungeobbang/backend/opinion/presentation/OpinionChatController.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/AdminOpinionServiceTest.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/MemberOpinionServiceTest.java, backend/src/test/java/com/bungeobbang/backend/opinion/service/OpinionServiceTest.java
- 채팅방 리스트 조회 최적화
- 
---
- java에서 정렬하던 것을 db에서 정렬하도록 변경
- 채팅 조회 시 본인이 작성한 채팅방인지 검증하는 로직 추가
---
- 
- 
---
- Closes #378 
- 관련 링크: 
---
=> [Feat/BE/#378] 채팅방 리스트 조회 수정

frontend/.storybook/preview.ts, frontend/src/components/Button.tsx, frontend/src/components/CategoryIcon.tsx, frontend/src/components/Chat/ChatSendField.tsx, frontend/src/components/Chat/ReceiverChat.tsx, frontend/src/components/Chat/SenderChat.tsx, frontend/src/components/Chat/TextBadge.tsx, frontend/src/components/Chip/ChipList.tsx, frontend/src/components/Dialog/DialogContainer.tsx, frontend/src/components/TopAppBar.tsx, frontend/src/components/bottom-navigation/BottomNavigation.tsx, frontend/src/components/tab-bar/TabBar.tsx, frontend/src/components/tab-bar/TabBarCotainer.tsx, frontend/src/components/text-field/CountTextField.tsx, frontend/src/components/text-field/TextField.tsx, frontend/src/stories/BottomNavigation.stories.tsx, frontend/src/stories/Button.stories.ts, frontend/src/stories/CategoryIcon.stories.ts, frontend/src/stories/ChatSendField.stories.tsx, frontend/src/stories/ChipList.stories.tsx, frontend/src/stories/CountTextField.stories.tsx, frontend/src/stories/Dialog.stories.tsx, frontend/src/stories/ReceiverChat.stories.tsx, frontend/src/stories/SenderChat.stories.tsx, frontend/src/stories/TabBar.stories.tsx, frontend/src/stories/TabBarContainer.stories.tsx, frontend/src/stories/TextBadge.stories.tsx, frontend/src/stories/TextField.stories.tsx, frontend/src/stories/TopAppBar.stories.ts
- 스토리북 Docs 추가
- 
---
- 
- 
---
- 
- 
---
- Closes #305 
- 관련 링크: 
---
=> [FEAT/FE/305] 스토리북 문서 추가

frontend/package-lock.json
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> chore: npm install

node_modules/.bin/husky, node_modules/.package-lock.json, node_modules/husky/LICENSE, node_modules/husky/README.md, node_modules/husky/bin.js, node_modules/husky/husky, node_modules/husky/index.d.ts, node_modules/husky/index.js, node_modules/husky/package.json, package.json
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> chore: husky 설치

frontend/.storybook/preview.ts, frontend/netlify.toml, frontend/src/components/bottom-navigation/BottomNavigation.tsx, frontend/src/components/tab-bar/TabBar.tsx, frontend/src/stories/BottomNavigation.stories.tsx, frontend/src/stories/Button.stories.ts, frontend/src/stories/CategoryIcon.stories.ts, frontend/src/stories/ChatSendField.stories.tsx, frontend/src/stories/ChipList.stories.tsx, frontend/src/stories/CountTextField.stories.tsx, frontend/src/stories/Dialog.stories.tsx, frontend/src/stories/ReceiverChat.stories.tsx, frontend/src/stories/SenderChat.stories.tsx, frontend/src/stories/TabBar.stories.tsx, frontend/src/stories/TabBarContainer.stories.tsx, frontend/src/stories/TextBadge.stories.tsx, frontend/src/stories/TextField.stories.tsx, frontend/src/stories/TopAppBar.stories.ts
- 스토리북 베이스 경로 수정
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> Storybook 배포

frontend/src/stories/ReceiverChat.stories.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> feat: 이미지 경로 수정

backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/AdminOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/MemberOpinionService.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionService.java
private 메서드를 public 아래로 위치 이동하였습니다!
=> [Refactor/BE] private 메서드 위치 변경

frontend/src/hooks/useImageUpload.ts
- 머지시에 생긴 conflict error 해결
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] image upload conflict error

backend/src/main/java/com/bungeobbang/backend/member/service/MemberService.java
- 
- 
---
- jwt에 대학id를 넣으면서 첫 회원가입 시 발생하는 npe 문제 해결
-
=> [Hotfix/Be] signup npe

backend/src/main/java/com/bungeobbang/backend/member/presentation/MemberController.java, backend/src/test/java/com/bungeobbang/backend/member/service/MemberServiceTest.java
- 첫 회원가입 시 발생하는 Npe 문제 해결
- 테스트코드 수정
=> [Hotfix/BE] 첫 회원가입 시 getUniversity npe 해결

frontend/src/components/tab-bar/TabBar.tsx, frontend/src/components/tab-bar/TabBarCotainer.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/admin/pages/statistics/index.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/my/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useInfiniteScroll.tsx, frontend/src/hooks/useScrollBottom.tsx, frontend/src/stories/TabBarContainer.stories.tsx, frontend/src/utils/chat/chat_const.ts
- 
- 
---
- 
- 
---
- 학생회 채팅방 리스트 중복으로 뜨던 문제 해결  
- 진행 중을 보는 중에 종료 채팅방 api 응답값을 렌더링하면 진행 중이 다시 렌더링되면서 또 요청하는 문제가 있었음
- 초반에 진행 중, 종료 api를 다같이 요청하고 응답받은 후 렌더링하도록 함
- 탭바 슬라이딩으로 이동 후 탭 아이템 선택하는 경우 itemId undefined 오류
- 탭바 이동은 translateX로 하고 scroll 은 scrollEvent로 하니까 이게 동기화가 안 되어서 문제였음
- 탭바 이동도 스크롤로 이동하도록 변경
---
- Closes #365 
- 관련 링크: 
---
=> [FEAT/FE/365] 학생회 채팅방 리스트 중복 & 탭바 itemId 오류

frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/admin/pages/opinion/entry/types.ts, frontend/src/store/socketStore.ts
- 빌드시 타입에러 해결
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] build error with admin opinion start socket event

backend/src/main/java/com/bungeobbang/backend/opinion/domain/repository/OpinionRepository.java, backend/src/main/java/com/bungeobbang/backend/opinion/service/OpinionRealTimeChatService.java
- 강제 종료 시 마지막 읽은 채팅 업데이트
- 
---
- 
- 
---
- 
- 
---
- Closes #420 
---
=> [Feat/BE/#420] 강제 종료 시 마지막 읽은 채팅 업데이트

backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
- 마지막 읽은 채팅이 MAX값인 답해요가 있을 경우에만 마지막 읽은 채팅을 업데이트한다.
- 
---
- 
- 
---
- Closes #420
- 관련 링크: 
---
=> [Fix/BE/#420] 마지막 읽은 채팅이 max인 값이 있을때만 update

backend/src/main/java/com/bungeobbang/backend/agenda/service/AgendaRealTimeChatService.java
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [Hotfix/BE/#420] 마지막 읽은 채팅이 Max값이 있을때만 update

frontend/src/components/Chat/ImagePreview.tsx, frontend/src/components/bottom-navigation/BottomNavigation.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/components/DurationContent.tsx, frontend/src/domains/admin/pages/agenda/create/index.tsx, frontend/src/domains/admin/pages/opinion/chatroom/index.tsx, frontend/src/domains/admin/pages/opinion/entry/index.tsx, frontend/src/domains/admin/pages/statistics/index.tsx, frontend/src/domains/student/App.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/login/emailcheck/index.tsx, frontend/src/domains/student/pages/login/univcheck/index.tsx, frontend/src/domains/student/pages/my/index.tsx, frontend/src/domains/student/pages/oauth/callback/index.tsx, frontend/src/domains/student/pages/opinion/chatroom/index.tsx, frontend/src/hooks/useChat.tsx, frontend/src/hooks/useQuery.ts, frontend/src/hooks/useSocketManager.ts, frontend/src/routes/AdminProtectedRoute.tsx, frontend/src/routes/StudentProtectedRoute.tsx, frontend/src/store/alarmStore.ts
- 이메일 인증 완료시 토큰 발급하도록 변경
- 캘린더 날짜 선택 에러 해결
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FEAT/FE] 이메일 인증 완료시 token 발급

backend/src/main/java/com/bungeobbang/backend/admin/service/AdminLoginService.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AgendaController.java
- controller에 누락되어있던 인가 어노테이션을 추가하였습니다.
- 
---
- Closes #
- 관련 링크: 
---
=> [Fix/BE] authorization 어노테이션 추가

backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/api/AdminAgendaApi.java
- adminonly를 위해 Accessor 파라미터가 필수인데 누락되어있어 추가합니다.
- 
---
=> [Fix/BE] accessor 누락 오류

frontend/src/components/bottom-navigation/BottomNavigation.tsx, frontend/src/components/text-field/RotatingMessage.tsx, frontend/src/domains/student/pages/opinion/entry/index.tsx, frontend/src/store/socketStore.ts
- 내가 보낸 채팅에 알람이 뜨는 에러
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 내가 보낸 채팅에 알람이 뜨는 에러

frontend/src/store/socketStore.ts
-  소켓 재연결 로직 제거 및 구독 관리
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 소켓 재연결 로직 제거

frontend/vite.config.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [TEST/FE] drop console

backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java, backend/src/main/java/com/bungeobbang/backend/agenda/presentation/AdminAgendaController.java, backend/src/main/java/com/bungeobbang/backend/agenda/service/AdminAgendaService.java
- 관리자의 소속 대학교 통계만 확인할 수 있도록 수정하였습니다.
=> [Fix/Be] 통계 university 추가

frontend/src/components/Chat/ChatSendField.tsx, frontend/src/domains/student/pages/agenda/chat/chat-page/index.tsx, frontend/src/hooks/useLoginDataInit.ts, frontend/src/store/socketStore.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] typo

frontend/vite.config.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: drop console false

backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
=> [Fix/BE] param 오타 수정

frontend/src/components/tab-bar/TabBarCotainer.tsx, frontend/src/domains/admin/pages/statistics/index.tsx
- TabContainer에서 선택 위치가 바뀌었음을 콜백으로 알려주어서 컨텐츠 내용 변경
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 통계 답해요로 바뀌지 않는 문제 해결

frontend/src/domains/admin/pages/agenda/index.tsx
- 학생회 채팅방 진행 중 개수 부족할 경우 진행 중 안 뜨는 문제 해결
- 진행 중 개수가 없을 경우 바로 진행 전을 요청하도록
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 학생회 채팅방 진행 중 개수 부족할 경우 진행 중 안 뜨는 문제 해결

frontend/src/index.css
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: iOS 스크롤 바운스 막기

frontend/src/hooks/useInfiniteScroll.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> feat: 추가 요청 시 딜레이

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/admin/pages/agenda/chat/chat-page/styles.ts, frontend/src/main.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: 바운스 막기

frontend/src/domains/admin/pages/agenda/chat/chat-page/index.tsx, frontend/src/domains/student/pages/agenda/index.tsx
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> [FIX/FE] 스크롤 막기 다시 해제

backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
=> [Fix/BE] agenda 조건문 오류 수정

backend/src/main/java/com/bungeobbang/backend/agenda/domain/infrastructure/CustomAgendaRepositoryImpl.java, backend/src/main/java/com/bungeobbang/backend/agenda/domain/repository/AgendaRepository.java
=> [Be] bug merge

frontend/src/domains/admin/pages/agenda/chat/chat-page/styles.ts, frontend/src/store/socketStore.ts
- 
- 
---
- 
- 
---
- 
- 
---
- Closes #
- 관련 링크: 
---
=> fix: 소켓 여러번 연결 오류 해결
